//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEEA.Helpers.Rsources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SEEA.Helpers.Rsources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TalkToSeeaHeader {
            get {
                return ResourceManager.GetString("TalkToSeeaHeader", resourceCulture);
            }
        }
        
        internal static string SearchEventsHeader {
            get {
                return ResourceManager.GetString("SearchEventsHeader", resourceCulture);
            }
        }
        
        internal static string SearchResultsHeader {
            get {
                return ResourceManager.GetString("SearchResultsHeader", resourceCulture);
            }
        }
        
        internal static string EventDetailsHeader {
            get {
                return ResourceManager.GetString("EventDetailsHeader", resourceCulture);
            }
        }
        
        internal static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        internal static string BookedEventsHeader {
            get {
                return ResourceManager.GetString("BookedEventsHeader", resourceCulture);
            }
        }
        
        internal static string SavedEventsHeader {
            get {
                return ResourceManager.GetString("SavedEventsHeader", resourceCulture);
            }
        }
        
        internal static string SavedSearchesHeader {
            get {
                return ResourceManager.GetString("SavedSearchesHeader", resourceCulture);
            }
        }
        
        internal static string TalkToSeeaButtonLabelText {
            get {
                return ResourceManager.GetString("TalkToSeeaButtonLabelText", resourceCulture);
            }
        }
        
        internal static string SearchEventButtonLabelText {
            get {
                return ResourceManager.GetString("SearchEventButtonLabelText", resourceCulture);
            }
        }
        
        internal static string GetInspiredButtonLabelText {
            get {
                return ResourceManager.GetString("GetInspiredButtonLabelText", resourceCulture);
            }
        }
        
        internal static string ProfileButtonLabelText {
            get {
                return ResourceManager.GetString("ProfileButtonLabelText", resourceCulture);
            }
        }
        
        internal static string SavesLockerButtonLabelText {
            get {
                return ResourceManager.GetString("SavesLockerButtonLabelText", resourceCulture);
            }
        }
        
        internal static string searchTextLabel {
            get {
                return ResourceManager.GetString("searchTextLabel", resourceCulture);
            }
        }
        
        internal static string dateLabel {
            get {
                return ResourceManager.GetString("dateLabel", resourceCulture);
            }
        }
        
        internal static string placeLabel {
            get {
                return ResourceManager.GetString("placeLabel", resourceCulture);
            }
        }
        
        internal static string organizationLabel {
            get {
                return ResourceManager.GetString("organizationLabel", resourceCulture);
            }
        }
        
        internal static string eventTypeLabel {
            get {
                return ResourceManager.GetString("eventTypeLabel", resourceCulture);
            }
        }
        
        internal static string saveSearchLabel {
            get {
                return ResourceManager.GetString("saveSearchLabel", resourceCulture);
            }
        }
        
        internal static string submitSearchButton {
            get {
                return ResourceManager.GetString("submitSearchButton", resourceCulture);
            }
        }
        
        internal static string searchNotSavedAlertHeader {
            get {
                return ResourceManager.GetString("searchNotSavedAlertHeader", resourceCulture);
            }
        }
        
        internal static string searchNotSavedAlertBody {
            get {
                return ResourceManager.GetString("searchNotSavedAlertBody", resourceCulture);
            }
        }
        
        internal static string dateErrorHeader {
            get {
                return ResourceManager.GetString("dateErrorHeader", resourceCulture);
            }
        }
        
        internal static string dateErrorWrongFormatBody {
            get {
                return ResourceManager.GetString("dateErrorWrongFormatBody", resourceCulture);
            }
        }
        
        internal static string dateErrorInPastBody {
            get {
                return ResourceManager.GetString("dateErrorInPastBody", resourceCulture);
            }
        }
        
        internal static string dateErrorHasCharactersBody {
            get {
                return ResourceManager.GetString("dateErrorHasCharactersBody", resourceCulture);
            }
        }
        
        internal static string dateErrorMoreThanFiveYearsBody {
            get {
                return ResourceManager.GetString("dateErrorMoreThanFiveYearsBody", resourceCulture);
            }
        }
        
        internal static string dateErrorGeneralBody {
            get {
                return ResourceManager.GetString("dateErrorGeneralBody", resourceCulture);
            }
        }
        
        internal static string searchResultEndOfList {
            get {
                return ResourceManager.GetString("searchResultEndOfList", resourceCulture);
            }
        }
        
        internal static string popupHeader {
            get {
                return ResourceManager.GetString("popupHeader", resourceCulture);
            }
        }
        
        internal static string showResultsWithThoseTagsLabel {
            get {
                return ResourceManager.GetString("showResultsWithThoseTagsLabel", resourceCulture);
            }
        }
        
        internal static string addSelectedTagsToLikedTagsLabel {
            get {
                return ResourceManager.GetString("addSelectedTagsToLikedTagsLabel", resourceCulture);
            }
        }
        
        internal static string showMatchesWithMyLikedTagsLabel {
            get {
                return ResourceManager.GetString("showMatchesWithMyLikedTagsLabel", resourceCulture);
            }
        }
        
        internal static string applyFilterButton {
            get {
                return ResourceManager.GetString("applyFilterButton", resourceCulture);
            }
        }
        
        internal static string bookNowButton {
            get {
                return ResourceManager.GetString("bookNowButton", resourceCulture);
            }
        }
        
        internal static string eventDiscriptionHeaderLabel {
            get {
                return ResourceManager.GetString("eventDiscriptionHeaderLabel", resourceCulture);
            }
        }
        
        internal static string costLabel {
            get {
                return ResourceManager.GetString("costLabel", resourceCulture);
            }
        }
        
        internal static string eventByLabel {
            get {
                return ResourceManager.GetString("eventByLabel", resourceCulture);
            }
        }
        
        internal static string welcomeLabel {
            get {
                return ResourceManager.GetString("welcomeLabel", resourceCulture);
            }
        }
        
        internal static string personalDataHeaderLabel {
            get {
                return ResourceManager.GetString("personalDataHeaderLabel", resourceCulture);
            }
        }
        
        internal static string nameLabel {
            get {
                return ResourceManager.GetString("nameLabel", resourceCulture);
            }
        }
        
        internal static string addressLabel {
            get {
                return ResourceManager.GetString("addressLabel", resourceCulture);
            }
        }
        
        internal static string emailLabel {
            get {
                return ResourceManager.GetString("emailLabel", resourceCulture);
            }
        }
        
        internal static string myReservationslabel {
            get {
                return ResourceManager.GetString("myReservationslabel", resourceCulture);
            }
        }
        
        internal static string reservedEventsEndOfList {
            get {
                return ResourceManager.GetString("reservedEventsEndOfList", resourceCulture);
            }
        }
        
        internal static string NoBookedEventsFirstLine {
            get {
                return ResourceManager.GetString("NoBookedEventsFirstLine", resourceCulture);
            }
        }
        
        internal static string NoBookedEventsSecondLine {
            get {
                return ResourceManager.GetString("NoBookedEventsSecondLine", resourceCulture);
            }
        }
        
        internal static string user_talk_entry {
            get {
                return ResourceManager.GetString("user_talk_entry", resourceCulture);
            }
        }
        
        internal static string tagCaptured {
            get {
                return ResourceManager.GetString("tagCaptured", resourceCulture);
            }
        }
        
        internal static string noTagCaptured {
            get {
                return ResourceManager.GetString("noTagCaptured", resourceCulture);
            }
        }
        
        internal static string myNameIs {
            get {
                return ResourceManager.GetString("myNameIs", resourceCulture);
            }
        }
        
        internal static string iAmFine {
            get {
                return ResourceManager.GetString("iAmFine", resourceCulture);
            }
        }
        
        internal static string youHave {
            get {
                return ResourceManager.GetString("youHave", resourceCulture);
            }
        }
        
        internal static string events {
            get {
                return ResourceManager.GetString("events", resourceCulture);
            }
        }
        
        internal static string oneEvent {
            get {
                return ResourceManager.GetString("oneEvent", resourceCulture);
            }
        }
        
        internal static string savedEventsEndOfList {
            get {
                return ResourceManager.GetString("savedEventsEndOfList", resourceCulture);
            }
        }
        
        internal static string savedSearchesEndOfList {
            get {
                return ResourceManager.GetString("savedSearchesEndOfList", resourceCulture);
            }
        }
        
        internal static string NoSearchesFirstLine {
            get {
                return ResourceManager.GetString("NoSearchesFirstLine", resourceCulture);
            }
        }
        
        internal static string NoSearchesSecondLine {
            get {
                return ResourceManager.GetString("NoSearchesSecondLine", resourceCulture);
            }
        }
        
        internal static string NoEventsFirstLine {
            get {
                return ResourceManager.GetString("NoEventsFirstLine", resourceCulture);
            }
        }
        
        internal static string NoEventsSecondLine {
            get {
                return ResourceManager.GetString("NoEventsSecondLine", resourceCulture);
            }
        }
    }
}
